// ignore: unused_import

import 'package:whatever_app/features/store/models/product_model.dart';
import 'package:whatever_app/utils/constants/image_strings.dart';

class TDummyData {
  static final List<ProductModel> products = [
    ProductModel(
      id: '001',
      title: 'Green Nike sports shoe',
      stock: 15,
      price: 135,
      thumbnail: TImages.productImage1,
      description: 'Green Nike sports shoe',
      images: [TImages.productImage1, TImages.productImage23, TImages.productImage21, TImages.productImage9],
      salePrice: 30,
      category: 'Clothes',
      sku: 'ABR4568',
    ),
    ProductModel(
      id: '002',
      title: 'Blue T-shirt for all ages',
      stock: 15,
      price: 35,
      thumbnail: TImages.productImage69,
      description:
          'This is a Product description for Blue Nike. Sleeve less vest. There are more things that can be added but i am just practicing and nothing else.',
      images: [TImages.productImage68, TImages.productImage69, TImages.productImage5],
      salePrice: 30,
      category: 'Clothes',
      sku: 'ABR4568',
    ),
    ProductModel(
      id: '003',
      title: 'Leather brown Jacket',
      stock: 15,
      price: 38000,
      thumbnail: TImages.productImage64,
      description:
          'This is a Product description for Leather brown Jacket. There are more things that can be added but i am just practicing and nothing else.',
      images: [TImages.productImage64, TImages.productImage65, TImages.productImage66, TImages.productImage67],
      salePrice: 30,
      category: 'Clothes',
      sku: 'ABR4568',
    ),
    ProductModel(
      id: '004',
      title: '4 Color collar t-shirt dry fit',
      stock: 15,
      price: 135,
      thumbnail: TImages.productImage60,
      description:
          'This is a Product description for 4 color collar t-shirt dry fit. There are more things that can be added but its just a demo and nothing else.',
      images: [TImages.productImage60, TImages.productImage61, TImages.productImage62, TImages.productImage63],
      salePrice: 30,
      category: 'Clothes',
      sku: 'ABR4568',
    ),
    ProductModel(
      id: '008',
      title: 'Adidas Running Shoes',
      stock: 20,
      price: 120,
      thumbnail: TImages.productImage24,
      description: 'Adidas Running Shoes for athletes. Comfortable and durable.',
      images: [TImages.productImage24, TImages.productImage25, TImages.productImage26],
      salePrice: 100,
      category: 'Clothes',
      sku: 'ABR4568',
    ),
    ProductModel(
      id: '009',
      title: 'Nike Air Jordon 19 Blue',
      stock: 15,
      price: 400,
      thumbnail: TImages.productImage19,
      description:
          'This is a Product description for Nike Air Jordon. There are more things that can be added but i am just practicing and nothing else.',
      images: [TImages.productImage19, TImages.productImage20, TImages.productImage21, TImages.productImage22],
      salePrice: 200,
      category: 'Clothes',
      sku: 'ABR4568',
    ),
    ProductModel(
      id: '010',
      title: 'Sony PlayStation 5',
      stock: 10,
      price: 499,
      thumbnail: TImages.productImage27,
      description: 'Sony PlayStation 5, the next-gen gaming console for immersive gaming experience.',
      images: [TImages.productImage27, TImages.productImage28, TImages.productImage29],
      salePrice: 479,
      category: 'Electronic',
      sku: 'ABR4568',
    ),
    ProductModel(
      id: '011',
      title: 'Canon EOS Rebel T7 DSLR Camera',
      stock: 5,
      price: 499,
      thumbnail: TImages.productImage30,
      description: 'Canon EOS Rebel T7 DSLR Camera for professional photography.',
      images: [TImages.productImage30, TImages.productImage31, TImages.productImage32],
      salePrice: 479,
      category: 'Electronic',
      sku: 'ABR4568',
    ),
    ProductModel(
      id: '012',
      title: 'Apple MacBook Pro 13-inch',
      stock: 8,
      price: 1299,
      thumbnail: TImages.productImage33,
      description: 'Apple MacBook Pro 13-inch for seamless computing experience.',
      images: [TImages.productImage33, TImages.productImage34, TImages.productImage35],
      salePrice: 1199,
      category: 'Electronic',
      sku: 'ABR4568',
    ),
    ProductModel(
      id: '013',
      title: 'LG 65-inch OLED 4K Smart TV',
      stock: 3,
      price: 1999,
      thumbnail: TImages.productImage36,
      description: 'LG 65-inch OLED 4K Smart TV for immersive viewing experience.',
      images: [TImages.productImage36, TImages.productImage37, TImages.productImage38],
      salePrice: 1899,
      category: 'Electronic',
      sku: 'ABR4568',
    ),
    ProductModel(
      id: '014',
      title: 'Xbox Series X',
      stock: 7,
      price: 499,
      thumbnail: TImages.productImage39,
      description: 'Xbox Series X, the ultimate gaming console for gamers.',
      images: [TImages.productImage39, TImages.productImage40, TImages.productImage41],
      salePrice: 479,
      category: 'Electronic',
      sku: 'ABR4568',
    ),
    ProductModel(
      id: '015',
      title: 'Fitbit Charge 4 Fitness Tracker',
      stock: 12,
      price: 149,
      thumbnail: TImages.productImage42,
      description: 'Fitbit Charge 4 Fitness Tracker for tracking your fitness activities.',
      images: [TImages.productImage42, TImages.productImage43, TImages.productImage44],
      salePrice: 129,
      category: 'Electronic',
      sku: 'ABR4568',
    ),
  ];
}
